language: objective-c
osx_image: xcode7.1
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=9.1,name=iPhone 6s" SCHEME="UberSignals iOS" SDK=iphonesimulator9.1
    - DESTINATION="platform=OS X,arch=x86_64" SCHEME="UberSignals OSX" SDK=macosx10.11
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - instruments -s devices
  - xcodebuild -project UberSignals.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" -sdk="SDK" -configuration Release ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c;
  - xcodebuild -project UberSignals.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" -sdk="SDK" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c;
notifications:
  email: false
